
export const _id = Array.from({ length: 40 }, (_, index) => `d4befda7-fdab-7ba5-a37s-5a5b4b6dacd${index + 1}`);


export const _emails = [
  "braydon_walter84@gmail.com",
  "serenity.zieme@gmail.com",
  "fletcher32@yahoo.com",
  "talia33@hotmail.com",
  "kamren29@gmail.com",
  "estelle.leannon@yahoo.com",
  "nathanael_hodkiewicz28@hotmail.com",
  "mackenzie30@yahoo.com",
  "judah.jakubowski55@yahoo.com",
  "cristian_wunsch19@yahoo.com",
  "hallie54@hotmail.com",
  "glennie58@gmail.com",
  "daryl_cronin94@hotmail.com",
  "clifford.gutmann60@yahoo.com",
  "jammie_mosciski25@gmail.com",
  "matilda64@yahoo.com",
  "favian_funk89@yahoo.com",
  "roxanne73@gmail.com",
  "adrian_mraz20@yahoo.com",
  "antonetta26@hotmail.com",
];

export const _fullNames = [
  "Cayden Doyle",
  "Amiya Vazquez",
  "Kylan Herman",
  "Athena Rios",
  "Adelina Le",
  "Harvey Mosley",
  "Curtis Phan",
  "Catalina Mccall",
  "Savion Mccormick",
  "Maren Meyers",
  "Adonis Huffman",
  "Adelina Mccormick",
  "Chaz Kirk",
  "Larae Frazier",
  "Alana Riggs",
  "Nash Hayden",
  "Jace Hayden",
  "Elvis Waller",
  "Kamryn Cannon",
  "Celia Mcintyre",
];

export const _fullAddress = [
  "4146 Rau Lane Apt. 346 - Burlington, NC / 61433",
  "283 Abbott Road Suite 353 - Bellflower, CA / 38902",
  "1431 VonRueden Parkway Apt. 929 - San Antonio, TX / 77025",
  "965 Raul Pike Apt. 624 - San Diego, CA / 48752",
  "964 Marvin Cliff Suite 663 - Chesapeake, VA / 30686",
  "9723 Ruben Circle Apt. 620 - San Antonio, TX / 91029",
  "496 Kuhn Ferry Apt. 778 - Omaha, NE / 49582",
  "7343 Hauck Dale Apt. 245 - Lexington, KY / 61084",
  "2142 Gusikowski Summit Suite 488 - Corpus Christi, TX / 64257",
  "9654 Baumbach Ville Apt. 209 - Evansville, IN / 53547",
  "8886 Kuphal Ports Suite 501 - San Francisco, CA / 35209",
  "2790 Bradtke Dale Suite 813 - Spokane, WA / 98034",
  "7185 Tillman Locks Apt. 768 - Springfield, IL / 50494",
  "24371 Queenie Brooks Apt. 238 - Chicago, IL / 60930",
  "854 Morissette Trail Suite 848 - Miami, FL / 40020",
  "3146 Ryan Rest Apt. 211 - Long Beach, CA / 69578",
  "80291 Judge Lodge Suite 871 - New York, NY / 89742",
  "9706 Flatley Highway Apt. 468 - Detroit, MI / 46592",
  "496 Marks Plaza Apt. 590 - Sacramento, CA / 39675",
  "31964 Hane Centers Apt. 903 - Philadelphia, PA / 56237",
];

export const _courseTitle = [
  "Web Development Bootcamp",
  "Photography Masterclass",
  "Digital Marketing Fundamentals",
  "Introduction to Machine Learning",
  "Financial Planning 101",
  "Yoga for Stress Relief",
  "Graphic Design Essentials",
  "Data Analysis with Python",
  "Creative Writing Workshop",
  "Public Speaking Mastery",
  "Interior Design Basics",
  "Investing in Stocks and Bonds",
  "Spanish Language Crash Course",
  "Mobile App Development for Beginners",
  "Cooking Techniques and Tips",
  "Artificial Intelligence Applications",
  "Entrepreneurship 101",
  "Music Production Fundamentals",
  "Fashion Design Fundamentals",
  "Gardening Tips and Tricks",
];
